steps:
- name: 'gcr.io/cloud-builders/docker'
  id: BUILD_INGRESS
  args:
    [
      'build', '-t', '${_IMAGE_INGRESS}',
      '-f', './Dockerfile.ingress-gcp',
      '--network=cloudbuild',
      '--platform', 'linux/amd64',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: PUSH_INGRESS
  args:
    [
      'push', '${_IMAGE_INGRESS}'
    ]

substitutions:
  _REPO: "ob-app-sidecar-repo"
  _REGISTRY: "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}"
  _NAME_INGRESS: "ob-app-sidecar-ingress"
  _IMAGE_INGRESS: "${_REGISTRY}/${_NAME_INGRESS}:${COMMIT_SHA}"

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
