# The validator container is a Go application.

# Application build.
FROM golang:1.23 AS stage-build
WORKDIR /usr/src/app
COPY cmd/cli ./cmd/cli
COPY go.mod ./
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /usr/local/bin/app ob-app-sidecar/cmd/cli

# Final image from build.
FROM scratch AS stage-final
COPY --from=stage-build /usr/local/bin/app /
EXPOSE 8082
CMD ["/app"]
