# The IAP validator container is a Go application.

# Application build.
FROM golang:1.23 AS stage-build
WORKDIR /usr/src/validator
COPY cmd/cli/validator-iap.go ./cmd/cli/validator-iap.go
COPY go.mod ./
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /usr/local/bin/validator-iap ob-app-sidecar/cmd/cli

# Final image from build.
FROM scratch AS stage-final
COPY --from=stage-build /usr/local/bin/validator-iap /
EXPOSE 8081
CMD ["/validator-iap"]
