# The backend container runs a Go application.

# Application build.
FROM golang:1.23 AS stage-build
WORKDIR /usr/src/app
COPY cmd/web ./cmd/web
COPY templates ./templates
COPY go.mod ./
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /usr/local/bin/app ob-app-sidecar/cmd/web

# Final image from build.
FROM scratch AS stage-final
COPY --from=stage-build /usr/local/bin/app /
COPY --from=stage-build /usr/src/app/templates /templates
EXPOSE 8082
CMD ["/app"]
