# The validator container is a Go application.

# Application build.
FROM golang:1.23 AS stage-build
WORKDIR /usr/src/validator
COPY backend/cmd/cli/validator-dummy.go ./cmd/cli/validator-dummy.go
COPY backend/go.mod ./
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /usr/local/bin/validator-dummy ob-app-sidecar/cmd/cli

# Final image from build.
FROM scratch AS stage-final
COPY --from=stage-build /usr/local/bin/validator-dummy /
EXPOSE 8081
CMD ["/validator-dummy"]
